### ISSUE TITLE
the top nav on Archive should be the same as Gallery.

### ISSUE THREAD

**Issue by alfski** [nobelharvards/PA1815#19]
The top nav menu needs to be consistent across all the pages.

eg. on the Archive page the , websocket sync and refresh icons disappear.

This is where a "single page app" wins... you right that code once!

**Comment by Carmeny1023** [comment]
I got rid of the WebSocket sync and refresh icon because the archive page doesn't use it...

I can add it to the archive page if you want. The same goes for other pages as well.

**Comment by alfski** [comment]
Because the site "feels" like a single page app (even though its not) it's odd that the topnav changes.

Knowing the websocket connection is alive is useful on every page.
