### ISSUE TITLE
360screen: transition fade between images

### ISSUE THREAD

**Issue by alfski** [nobelharvards/PA1815#7]
We can do better than 'hard refresh'.

setup  two img divs and use opacity transition between them over 500ms.

**Comment by helio232** [comment]
Image comes in and then the image turns off and then the image shows up 
Remove x
Change from modal, no background or anything to be viewed
This is why xyfi is important
Replace div – does notneed to be materialize css – change from modal – no keyboard or mouse 
Image shows fade to black – show new image 
Replace image with new image 
When switching images the black image comes forward then fades out – frame buffer
Two divs one in front is visible and then load up middle and then fade out the other. Swap depths of the two panels. 
Upto you make it look more polished fade the one in front to black first. The double buffer is a good way to do this but there are other options. 
Issue fade outl; 
You can keep materialize if you want.
